In [197]:
# importing python libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [198]:
# installing pyreadstat module
!pip install pyreadstat

Requirement already satisfied: pyreadstat in /usr/local/lib/python3.12/dist-packages (1.3.3)
Requirement already satisfied: narwhals>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.18.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.0.2)

In [199]:
heart_data = pd.read_csv('/content/HeartDiseaseTrain-Test.csv')

In [200]:
heart_data.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,52,Male,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,No,1.0,Downsloping,Two,Reversable Defect,0
1,53,Male,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,Yes,3.1,Upsloping,Zero,Reversable Defect,0
2,70,Male,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,Yes,2.6,Upsloping,Zero,Reversable Defect,0
3,61,Male,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,No,0.0,Downsloping,One,Reversable Defect,0
4,62,Female,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,No,1.9,Flat,Three,Fixed Defect,0

In [201]:
heart_data.shape

(1025, 14)

In [202]:
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            1025 non-null   int64
 1   sex                            1025 non-null   object
 2   chest_pain_type                1025 non-null   object
 3   resting_blood_pressure         1025 non-null   int64
 4   cholestoral                    1025 non-null   int64
 5   fasting_blood_sugar            1025 non-null   object
 6   rest_ecg                       1025 non-null   object
 7   Max_heart_rate                 1025 non-null   int64
 8   exercise_induced_angina        1025 non-null   object
 9   oldpeak                        1025 non-null   float64
 10  slope                          1025 non-null   object
 11  vessels_colored_by_flourosopy  1025 non-null   object
 12  thalassemia                    1025 non-null   object
 13  target                         1025 non-null   int64
dtypes: float64(1), int64(5), object(8)
memory usage: 112.2+ KB

In [203]:
heart_data.isnull().sum()

age                              0
sex                              0
chest_pain_type                  0
resting_blood_pressure           0
cholestoral                      0
fasting_blood_sugar              0
rest_ecg                         0
Max_heart_rate                   0
exercise_induced_angina          0
oldpeak                          0
slope                            0
vessels_colored_by_flourosopy    0
thalassemia                      0
target                           0
dtype: int64

In [204]:
# statistical measures of data
heart_data.describe()

,age,resting_blood_pressure,cholestoral,Max_heart_rate,oldpeak,target
count,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000
mean,54.434146,131.611707,246.00000,149.114146,1.071512,0.513171
std,9.072290,17.516718,51.59251,23.005724,1.175053,0.500070
min,29.000000,94.000000,126.00000,71.000000,0.000000,0.000000
25%,48.000000,120.000000,211.00000,132.000000,0.000000,0.000000
50%,56.000000,130.000000,240.00000,152.000000,0.800000,1.000000
75%,61.000000,140.000000,275.00000,166.000000,1.800000,1.000000
max,77.000000,200.000000,564.00000,202.000000,6.200000,1.000000

In [205]:
# checking the distribution of Target Variable
heart_data['target'].value_counts()

target
1    526
0    499
Name: count, dtype: int64

1 --> Defective Heart
0 --> Healthy Heart

Splitting the features and target

In [206]:
X = heart_data.drop(columns='target', axis=1)
Y = heart_data['target']

In [207]:
print(X)

      age     sex  chest_pain_type  resting_blood_pressure  cholestoral  \
0      52    Male   Typical angina                     125          212
1      53    Male   Typical angina                     140          203
2      70    Male   Typical angina                     145          174
3      61    Male   Typical angina                     148          203
4      62  Female   Typical angina                     138          294
...   ...     ...              ...                     ...          ...
1020   59    Male  Atypical angina                     140          221
1021   60    Male   Typical angina                     125          258
1022   47    Male   Typical angina                     110          275
1023   50  Female   Typical angina                     110          254
1024   54    Male   Typical angina                     120          188

         fasting_blood_sugar               rest_ecg  Max_heart_rate  \
0       Lower than 120 mg/ml  ST-T wave abnormality             168
1     Greater than 120 mg/ml                 Normal             155
2       Lower than 120 mg/ml  ST-T wave abnormality             125
3       Lower than 120 mg/ml  ST-T wave abnormality             161
4     Greater than 120 mg/ml  ST-T wave abnormality             106
...                      ...                    ...             ...
1020    Lower than 120 mg/ml  ST-T wave abnormality             164
1021    Lower than 120 mg/ml                 Normal             141
1022    Lower than 120 mg/ml                 Normal             118
1023    Lower than 120 mg/ml                 Normal             159
1024    Lower than 120 mg/ml  ST-T wave abnormality             113

     exercise_induced_angina  oldpeak        slope  \
0                         No      1.0  Downsloping
1                        Yes      3.1    Upsloping
2                        Yes      2.6    Upsloping
3                         No      0.0  Downsloping
4                         No      1.9         Flat
...                      ...      ...          ...
1020                     Yes      0.0  Downsloping
1021                     Yes      2.8         Flat
1022                     Yes      1.0         Flat
1023                      No      0.0  Downsloping
1024                      No      1.4         Flat

     vessels_colored_by_flourosopy        thalassemia
0                              Two  Reversable Defect
1                             Zero  Reversable Defect
2                             Zero  Reversable Defect
3                              One  Reversable Defect
4                            Three       Fixed Defect
...                            ...                ...
1020                          Zero       Fixed Defect
1021                           One  Reversable Defect
1022                           One       Fixed Defect
1023                          Zero       Fixed Defect
1024                           One  Reversable Defect

[1025 rows x 13 columns]

In [208]:
print(Y)

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

Splitting the data into training data and test data

In [209]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [210]:
print(X.shape, X_train.shape, X_test.shape)

(1025, 13) (820, 13) (205, 13)

In [211]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

X_train = pd.get_dummies(X_train,drop_first=True)
X_test = pd.get_dummies(X_test,drop_first=True)

X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

# Store column names for later use in prediction
feature_columns_after_dummies = X_train.columns

In [212]:
X_test

,age,resting_blood_pressure,cholestoral,Max_heart_rate,oldpeak,sex_Male,chest_pain_type_Atypical angina,chest_pain_type_Non-anginal pain,chest_pain_type_Typical angina,fasting_blood_sugar_Lower than 120 mg/ml,...,exercise_induced_angina_Yes,slope_Flat,slope_Upsloping,vessels_colored_by_flourosopy_One,vessels_colored_by_flourosopy_Three,vessels_colored_by_flourosopy_Two,vessels_colored_by_flourosopy_Zero,thalassemia_No,thalassemia_Normal,thalassemia_Reversable Defect
845,56,132,184,105,2.1,True,False,False,True,True,...,True,True,False,True,False,False,False,False,True,False
542,62,140,394,157,1.2,False,False,False,True,True,...,False,True,False,False,False,False,True,False,False,False
147,41,110,172,158,0.0,True,False,False,True,True,...,False,False,False,False,False,False,True,False,False,True
711,35,120,198,130,1.6,True,False,False,True,True,...,True,True,False,False,False,False,True,False,False,True
724,74,120,269,121,0.2,False,True,False,False,True,...,True,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,63,150,407,154,4.0,False,False,False,True,True,...,False,True,False,False,True,False,False,False,False,True
563,44,112,290,153,0.0,True,False,False,True,True,...,False,False,False,True,False,False,False,False,False,False
654,41,126,306,163,0.0,False,True,False,False,True,...,False,False,False,False,False,False,True,False,False,False
943,65,120,177,140,0.4,True,False,False,True,True,...,False,False,False,False,False,False,True,False,False,True
734,52,128,204,156,1.0,True,False,False,True,False,...,True,True,False,False,False,False,True,True,False,False

In [213]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

**MODEL TRAINING**

Logistic Regression

In [214]:
lr_model = LogisticRegression(max_iter=1500)
lr_model.fit(X_train,Y_train)

# Predictions
lr_train_prediction = lr_model.predict(X_train)
lr_test_prediction = lr_model.predict(X_test)

#Accuracy
lr_train_data_accuracy = accuracy_score(lr_train_prediction, Y_train)
lr_test_data_accuracy = accuracy_score(lr_test_prediction, Y_test)

print('Accuracy on Training data : ', lr_train_data_accuracy)
print('Accuracy on Test data : ', lr_test_data_accuracy)

Accuracy on Training data :  0.8780487804878049
Accuracy on Test data :  0.8439024390243902

In [215]:
print("Confusion Matrix:\n", confusion_matrix(Y_test, lr_test_prediction))
print("\nClassification Report:\n", classification_report(Y_test, lr_test_prediction))

Confusion Matrix:
 [[81 19]
 [13 92]]

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.81      0.84       100
           1       0.83      0.88      0.85       105

    accuracy                           0.84       205
   macro avg       0.85      0.84      0.84       205
weighted avg       0.84      0.84      0.84       205

Decision Tree

In [216]:
dt_model = DecisionTreeClassifier(max_depth=4,random_state=42)
dt_model.fit(X_train, Y_train)

# Predictions
dt_train_prediction = dt_model.predict(X_train)
dt_test_prediction = dt_model.predict(X_test)

# Accuracy
dt_train_data_accuracy = accuracy_score(dt_train_prediction, Y_train)
dt_test_data_accuracy = accuracy_score(dt_test_prediction, Y_test)

print("Accuracy on Training data:", dt_train_data_accuracy)
print("Accuracy on Test data:", dt_test_data_accuracy)

Accuracy on Training data: 0.8780487804878049
Accuracy on Test data: 0.8634146341463415

In [217]:
print("Confusion Matrix:\n", confusion_matrix(Y_test, dt_test_prediction))
print("\nClassification Report:\n", classification_report(Y_test, dt_test_prediction))

Confusion Matrix:
 [[84 16]
 [12 93]]

Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.84      0.86       100
           1       0.85      0.89      0.87       105

    accuracy                           0.86       205
   macro avg       0.86      0.86      0.86       205
weighted avg       0.86      0.86      0.86       205

Model Evaluation

In [218]:
print("Model Prediction Summary:")
print("Logistic Regression Test Accuracy:",lr_test_data_accuracy)
print("Decision Tree Test Accuracy:",dt_test_data_accuracy)

Model Prediction Summary:
Logistic Regression Test Accuracy: 0.8439024390243902
Decision Tree Test Accuracy: 0.8634146341463415

Building a Prediction System

In [219]:
input_data = pd.DataFrame([
    {
        'age': 63,
        'sex': 'Female',
        'chest_pain_type': 'Non-anginal angina',
        'resting_blood_pressure': 135,
        'cholestoral': 252,
        'fasting_blood_sugar': 'Lower than 120 mg/ml',
        'rest_ecg': 'Normal',
        'Max_heart_rate': 172,
        'exercise_induced_angina': 'No',
        'oldpeak': 0,
        'slope': 'Downsloping',
        'vessels_colored_by_flourosopy': 'Zero',
        'thalassemia': 'Fixed Defect'
    }
])

input_data = pd.get_dummies(input_data)

# Align with training data columns saved before scaling
input_data = input_data.reindex(columns=feature_columns_after_dummies, fill_value=0)

# Scale the input data using the trained scaler
input_data_scaled = scaler.transform(input_data)

In [220]:
# Use the scaled input data directly for prediction
prediction = model.predict(input_data_scaled)

if (prediction[0] == 0):
  print('The Person does not have a Heart Disease')
else:
  print('The Person has Heart Disease')

The Person has Heart Disease